### ISSUE TITLE
PingWithTimeout does not set timeout for internal SRVResolve

### ISSUE THREAD

**Issue by AlexanderMatveev** [iverly/go-mcping#1]
I'm calling `PingWithTimeout` with and it hangs on some domain names, despite timeout parameter.

**Comment by MarvinKlar** [comment]
I am facing a similar issue when using `PingWithTimeout`. I encounter latencies of 101379ms or higher. This only happens, when the server I am pinging is currently starting. It only resonds when started completely. The request sent with `PingWithTimeout` is taking as long, as the startup takes.
I'm using `response, err := pinger.PingWithTimeout(hostname, port, 3*time.Second)`.

**Comment by iverly** [comment]
> I debugged this and it seems like `ReadUvarint` in `readResponse` in `writer.go` is stuck as long as the server needs to fulfill the request. The used `binary` package does not provide a timeout itself.
> 
> 
> 
> If I would implement a timeout, would you merge this @iverly? :)

Hi,

Thank you for debugging this issue. 

Of course, I'll merge it 😉.

**Comment by MarvinKlar** [comment]
Did so :) Let me know, if there is anything to improve @iverly!

**Comment by AlexanderMatveev** [comment]
This issue can be solved easily by wrapping with `context.WithTimeout` 🙂
